name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages Configuration
        uses: actions/configure-pages@v4

      - name: Upload Static Web Files
        uses: actions/upload-pages-artifact@v3
        with:
          # This uploads your index.html directly from your main folder
          path: '.'

      - name: Deploy Live Site
        id: deployment
        uses: actions/deploy-pages@v4
